artifacts_root: artifacts #this will create a artifacts folder that will save all the generations from the componets

#creating data ingestion configurations this stores all the URL needed for the project

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#Inside artifacts it will create a folder data_validation inside which all validation related atrifacts will be stored
#It will create a txt file and check wether the tran, test, validation files are available 
#depeding on which the staus file will be true or false
data_validation:
    root_dir: artifacts/data_validation
    STATUS_FILE: artifacts/data_validation/status.txt
    ALL_REQUIRED_FILES: ["train","test","validation"]